src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $photo_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPhotoId(): ?int
    {
        return $this->photo_id;
    }

    public function setPhotoId(int $photo_id): self
    {
        $this->photo_id = $photo_id;

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Repository\ArticleRepository;
use App\Repository\PhotoRepository;
use App\Service\Storage\S3FileStorage;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{
    /**
     * @var S3FileStorage $s3FileStorage
     */
    private $s3FileStorage;

    /**
     * @var PhotoRepository $photoRepository
     */
    private $photoRepository;

    /**
     * @var ArticleRepository $articleRepository
     */
    private $articleRepository;

    private $paginator;

    public function __construct(
        S3FileStorage $s3FileStorage,
        PhotoRepository $photoRepository,
        ArticleRepository $articleRepository,
        PaginatorInterface $paginator
    ) {
        $this->s3FileStorage = $s3FileStorage;
        $this->photoRepository = $photoRepository;
        $this->articleRepository = $articleRepository;
        $this->paginator = $paginator;
    }

    /**
     * @Route("/blog/{page}", name="blog")
     *
     * @param ArticleRepository $articleRepository
     * @param int $page
     *
     * @return Response
     */
    public function index(ArticleRepository $articleRepository, int $page = 1)
    {
        $queryBuilder = $articleRepository->getQueryBuilder();
        $pagination = $this->paginator->paginate(
            $queryBuilder,
            $page,
            3
        );

        $photos = $this->photoRepository->getList(1, 7);

        return $this->render('blog/index.html.twig', [
            'photos' => $photos,
            'pagination' => $pagination
        ]);
    }

    /**
     * @Route("/blog/article/{id}", name="article")
     *
     * @param int $id
     *
     * @return Response
     */
    public function article(int $id)
    {
        $article = $this->articleRepository->find($id);
        $photos = $this->photoRepository->getList(1, 7);

        return $this->render('blog/article.html.twig', [
            'article' => $article,
            'photos' => $photos
        ]);
    }
}

templates/blog/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AboutController!{% endblock %}

{% block social_sidebar_area %}
    <!-- Social Sidebar Area Start -->
    <div class="social-sidebar-area">
        <!-- Social Area -->
        {% include 'common/social_info_area.html.twig' %}
    </div>
    <!-- Social Sidebar Area End -->
{% endblock %}

{% block body %}
    <!-- About Me Area Start -->
    <section class="about-me-area mt-100 section_padding_100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-10">
                    <div class="about-me-thumb">
                        <img src="{{ storage.getPhotoUrl(article.photoId) }}" alt="">
                    </div>
                </div>
                <div class="col-10">
                    <div class="about-content mt-100 mb-100 text-center">
                        <span></span>
                        <h2>{{ article.title }}</h2>
                        <p>{{ article.text }}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About Me Area End -->
{% endblock %}

{% block footer %}
    {% include 'common/follow_me_instagram.html.twig' %}
    {% include 'common/footer_row.html.twig' %}
    {% include 'common/copyright_row.html.twig' %}
{% endblock %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BlogController!{% endblock %}

{% block header %}
    {{ parent() }}

    {% block header_area %}
        <header class="header-area bg-img" style="background-image: url(img/bg-img/14.jpg);">
            {% include 'common/header_row.html.twig' %}
        </header>
    {% endblock %}

{% endblock %}

{% block body %}
    <!-- Blog Area Start -->
    <section class="blog-area section_padding_100 mt-100">
        <div class="container">
            <div class="row justify-content-center">
                {% for article in pagination %}
                <!-- Single Blog Area -->
                    <div class="col-10">
                        <div class="single-blog-area text-center mb-100 wow fadeInUpBig" data-wow-delay="100ms" data-wow-duration="1s">
                            <div class="blog-thumbnail mb-100">
                                <img src="{{ storage.getPhotoUrl(article.getPhotoId()) }}" alt="">
                            </div>
                            <div class="blog-content">
                                <span></span>
                                <h2>{{ article.getTitle() }}</h2>
                                <a href="#" class="post-date">{{ article.getDate().format('F j, Y') }}</a>
                                <a href="{{ path('about') }}" class="post-author">By Maxim Kravets</a>
                                <p>{{ article.getText() }}</p>
                                <a href="{{ path('article', {'id': article.getId()}) }}" class="btn studio-btn"><img src="{{ asset('img/core-img/logo-icon.png') }}" alt=""> Read More</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <!-- Pagination -->
            <div class="row">
                <div class="col-12">
                    <nav aria-label="Page navigation" class="pagination-area mb-100">
                        <ul class="pagination justify-content-center">
                            {{ knp_pagination_render(pagination) }}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Area End -->
{% endblock %}

{% block footer %}
    {% include 'common/footer_row.html.twig' %}
    {% include 'common/copyright_row.html.twig' %}
{% endblock %}